2018-11-09 13:33:40,838 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:33:44,526 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:34:57,468 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:35:37,706 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:36:02,083 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:37:03,941 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:42:16,913 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:42:30,014 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:42:56,167 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:43:58,930 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:44:02,961 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:44:09,685 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:44:15,252 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:46:23,986 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:46:27,708 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:47:35,628 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:48:42,077 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:48:59,293 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:49:44,094 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:51:39,473 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:52:43,283 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:52:53,323 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:53:35,693 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:53:52,389 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:53:59,945 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:54:43,465 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:55:12,191 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:55:20,387 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:55:28,956 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:55:34,511 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:56:58,080 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:57:04,774 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:57:50,072 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:58:13,807 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:58:51,075 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 13:59:34,248 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:01:19,859 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:01:28,476 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:01:55,931 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:02:33,595 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:02:41,219 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:02:51,870 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:06:34,124 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:06:37,909 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:06:39,343 ERROR: Exception on / [GET] [in /Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/duarteocarmo/SourceTree_Repos/dev.pt/app/routes.py", line 19, in index
    posts = Post.query.order_by(Post.get_score.desc()).all()
AttributeError: 'function' object has no attribute 'desc'
2018-11-09 14:06:55,908 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:06:57,212 ERROR: Exception on / [GET] [in /Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/duarteocarmo/SourceTree_Repos/dev.pt/app/routes.py", line 19, in index
    posts = Post.query.order_by(Post.get_score).all()
  File "<string>", line 2, in order_by
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1716, in order_by
    criterion = self._adapt_col_list(criterion)
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 292, in _adapt_col_list
    for o in cols
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 292, in <listcomp>
    for o in cols
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 4266, in _literal_as_label_reference
    return _literal_as_text(element)
  File "/Users/duarteocarmo/anaconda/envs/dev.to/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 4305, in _literal_as_text
    "instead" % type(element)
sqlalchemy.exc.ArgumentError: SQL expression object or string expected, got object of type <class 'function'> instead
2018-11-09 14:07:13,361 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:07:37,547 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:16:12,990 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:16:27,114 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:17:25,050 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:17:35,015 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:17:37,074 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:19:29,491 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:20:05,108 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:20:25,202 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:21:22,640 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
2018-11-09 14:21:41,393 INFO: Devpt startup [in /Users/duarteocarmo/SourceTree_Repos/dev.pt/app/__init__.py:34]
